# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZRDownload' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ZRDownload

pod 'ZRProgressView', '~> 0.0.6'

pod 'AFNetworking', '~> 3.2.1'

pod 'Masonry', '~> 1.1.0'

pod 'ZRControllerTranstion', '~> 0.0.3'

end
